### ISSUE TITLE
This step of 512 resize is superfluous

### ISSUE THREAD

**Issue by jjandnn** [tg-bomze/Video2Drawing#1]
Прежде всего, я хотел бы сказать, что каждый раз, когда вы смотрите colab-версию последних популярных программ, сделанных на максимальной скорости, это здорово.
Вы экономите время для всех, это потрясающе.
Но на этот раз у этого проекта, кажется, есть еще один шаг.
Поскольку оригинальная работа, включая оригинальный проект adp автора, он сократил ее до 512, чтобы гарантировать, что лицо находится в разумной центральной области, поэтому, когда стиль преобразуется, программа выделяет лицо.
Сам test.py автоматически генерирует 512 * 512 графиков любого размера, поэтому вам не нужно изменять размер при генерации последовательностей.
Кроме того, ядром авторского проекта является преобразование стиля, которое отличается от обработки лица, то есть до тех пор, пока часть изображения с сильным контрастом автоматически преобразуется в рисунок.
Если вы хотите восстановить видео в любом соотношении входного сигнала, просто измените размер предпоследнего шага перед синтезом видео.
Прости меня за мой английский и русский, я хуже твоего, хахаха.
Удачи
首先，我想说，每次看你以最快的速度制作最新的各类热门程序的colab版本，很棒。
你为大伙儿节省时间，很了不起。
不过这次，这个项目，你似乎多了一个步骤。
因为原作，包括原作者的adp项目，他裁剪成512，是为了确保面部在合理的中心区域，这样风格转化的时候，程序会突出面部。
test.py本身就是自动把任何尺寸的图生成512*512，所以你生成序列时，不用resize。
另外，该作者的项目核心是风格转化，不同于脸部处理类，也就是说，只要是画面中对比度强的部分都会自动处理成draw。
你如果想把视频还原成输入的任何比例，只需要在合成视频前，即倒数第二步resize就可以了。
原谅我的英语和俄语，我两样都比你的还糟糕，哈哈哈。
祝顺利！
First of all, I would like to say that every time you watch the colab version of the latest popular programs made at the fastest speed, it is great.

You save time for everyone, it's amazing.

But this time, this project, you seem to have one more step.

Because the original work, including the original author's adp project, he cut it to 512, to ensure that the face is in a reasonable central area, so when the style is transformed, the program will highlight the face.

test.py itself automatically generates 512 * 512 graphs of any size, so you do n’t need to resize when generating sequences.

In addition, the core of the author's project is style conversion, which is different from face processing. That is to say, as long as the part of the picture with strong contrast is automatically processed into draw.

If you want to restore the video to any ratio of the input, just resize the penultimate step before synthesizing the video.

Forgive me for my English and Russian, I am worse than yours, hahaha.

Good luck!

**Comment by tg-bomze** [comment]
Thank you very much for your comment. I will take this into account.
